### ISSUE TITLE
facetPlot

### ISSUE THREAD

**Issue by michaelnoe** [CRUKMI-ComputationalBiology/twoddpcr#2] opened 2018-01-08 16:33 UTC
when i try plotLimits in the facetPlot, it doesn't incorporate my limits to the plot...

**Comment by idno0001** [comment] 2018-01-09 16:37
I cannot reproduce this problem.

Are you perhaps trying to set `plotLimits` so that it crops the plot (so you are trying to shrink the plot area)? If so, this doesn't work for methodological reasons: when viewing a plot, the package is designed to allow us to see _all_ of the droplets. In the particular case of `facetPlot`, we want to be able to compare droplet intensities across all of the wells. Therefore the limits are the same for all of the plots.

If this is not the case, can you provide more details? e.g. the code you are using.

**Comment by michaelnoe** [comment] 2018-01-09 16:46
I'm sorry: this is the problem: I use cMethod:"Cluster" to use the initial clustering, done with QuantaSoft from BioRad... When I don't use that, it is able to trim the plot so the dots are spread nicely over the plot. However, when I use the cMethod, it doesn't trim the plots (all the dots are in one corner...

So it works with: 
`facetPlot(plate, plotLimits = list(x = c(1000, 5000), y = c(1000, 7000)))`
but doesn't work with: 
`facetPlot(plate, cMethod="Cluster", plotLimits = list(x=c(1000,5000), y=c(1000, 7000)))`

Alle the dots are between these beacons...

**Comment by idno0001** [comment] 2018-01-12 11:07
Thank you for the extra information. This is now fixed in the latest version on Bioconductor. Let me know if this does not work for you.

**Closed by idno0001** 2018-01-12 11:07 UTC
